<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Decision Trees Quarto - Enhanced Analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Decision Tree Quarto_files/libs/clipboard/clipboard.min.js"></script>
<script src="Decision Tree Quarto_files/libs/quarto-html/quarto.js"></script>
<script src="Decision Tree Quarto_files/libs/quarto-html/popper.min.js"></script>
<script src="Decision Tree Quarto_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Decision Tree Quarto_files/libs/quarto-html/anchor.min.js"></script>
<link href="Decision Tree Quarto_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Decision Tree Quarto_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Decision Tree Quarto_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Decision Tree Quarto_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Decision Tree Quarto_files/libs/bootstrap/bootstrap-c0367b04c37547644fece4185067e4a7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Decision Trees Quarto - Enhanced Analysis</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="data-preparation" class="level1">
<h1>Data Preparation</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load required libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caTools)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Boruta)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(cvms)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load training data</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>flight_data_train <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"~/FlightProject/flight_data_train.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>() <span class="sc">%&gt;%</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>data_set_division)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Load test data  </span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>flight_data_test <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"~/FlightProject/flight_data_test.csv"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>()<span class="sc">%&gt;%</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>data_set_division)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Display training data structure</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(flight_data_train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 8,477
Columns: 26
$ Airline                  &lt;chr&gt; "IndiGo", "IndiGo", "SpiceJet", "Jet Airways"…
$ Date_of_Journey          &lt;chr&gt; "12/05/2019", "01/03/2019", "24/06/2019", "12…
$ departure_date_time      &lt;dttm&gt; 2019-05-12 18:05:00, 2019-03-01 16:50:00, 20…
$ Departure_Day            &lt;dbl&gt; 12, 1, 24, 12, 1, 27, 1, 18, 24, 3, 15, 12, 1…
$ Departure_Month          &lt;dbl&gt; 5, 3, 6, 3, 3, 5, 6, 4, 6, 3, 4, 6, 6, 5, 3, …
$ Departure_Year           &lt;dbl&gt; 2019, 2019, 2019, 2019, 2019, 2019, 2019, 201…
$ Departure_Time           &lt;time&gt; 18:05:00, 16:50:00, 09:00:00, 18:55:00, 08:0…
$ arrival_date_time        &lt;dttm&gt; 2019-05-12 23:30:00, 2019-03-01 21:35:00, 20…
$ Arrival_Day              &lt;dbl&gt; 12, 1, 24, 13, 2, 27, 1, 18, 24, 4, 15, 13, 1…
$ Arrival_Month            &lt;dbl&gt; 5, 3, 6, 3, 3, 5, 6, 4, 6, 3, 4, 6, 6, 5, 3, …
$ Arrival_Time             &lt;time&gt; 23:30:00, 21:35:00, 11:25:00, 10:25:00, 05:0…
$ Duration                 &lt;chr&gt; "5h 25m", "4h 45m", "2h 25m", "15h 30m", "21h…
$ Source                   &lt;chr&gt; "Kolkata", "Banglore", "Kolkata", "Banglore",…
$ Destination              &lt;chr&gt; "Banglore", "Delhi", "Banglore", "Delhi", "De…
$ airport_code_departure   &lt;chr&gt; "CCU", "BLR", "CCU", "BLR", "BLR", "DEL", "DE…
$ airport_code_first_stop  &lt;chr&gt; "NAG", "NAG", NA, "BOM", "BOM", "BOM", "BLR",…
$ airport_code_second_stop &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, "BOM", NA…
$ airport_code_third_stop  &lt;chr&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, N…
$ airport_code_arrival     &lt;chr&gt; "BLR", "DEL", "BLR", "DEL", "DEL", "COK", "CO…
$ Route                    &lt;chr&gt; "CCU → NAG → BLR", "BLR → NAG → DEL", "CCU → …
$ Total_Stops              &lt;chr&gt; "1 stop", "1 stop", "non-stop", "1 stop", "1 …
$ Price                    &lt;dbl&gt; 6218, 13302, 3873, 11087, 22270, 8625, 8907, …
$ Additional_Info          &lt;chr&gt; "No info", "No info", "No info", "In-flight m…
$ departure_day_of_week    &lt;chr&gt; "Sunday", "Friday", "Monday", "Tuesday", "Fri…
$ Departure_Hour           &lt;dbl&gt; 18, 16, 9, 18, 8, 11, 9, 20, 11, 16, 8, 14, 2…
$ Duration_Hours           &lt;dbl&gt; 5.416667, 4.750000, 2.416667, 15.500000, 21.0…</code></pre>
</div>
</div>
<p>Replacing the missing values for airport stops with NONE.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>flight_data_train <span class="ot">&lt;-</span> flight_data_train <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Replace missing airport stops with "NONE" </span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">airport_code_first_stop =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(airport_code_first_stop), <span class="st">"NONE"</span>, airport_code_first_stop),</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">airport_code_second_stop =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(airport_code_second_stop), <span class="st">"NONE"</span>, airport_code_second_stop),</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">airport_code_third_stop =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(airport_code_third_stop), <span class="st">"NONE"</span>, airport_code_third_stop)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>flight_data_test <span class="ot">&lt;-</span> flight_data_test <span class="sc">%&gt;%</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Replace missing airport stops with "NONE" </span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">airport_code_first_stop =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(airport_code_first_stop), <span class="st">"NONE"</span>, airport_code_first_stop),</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">airport_code_second_stop =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(airport_code_second_stop), <span class="st">"NONE"</span>, airport_code_second_stop),</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">airport_code_third_stop =</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(airport_code_third_stop), <span class="st">"NONE"</span>, airport_code_third_stop)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="feature-engineering" class="level2">
<h2 class="anchored" data-anchor-id="feature-engineering">Feature Engineering</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create engineered features for training data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>flight_data_train_processed <span class="ot">&lt;-</span> flight_data_train <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Convert categorical stops to numeric feature</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">number_of_stops =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>      Total_Stops <span class="sc">==</span> <span class="st">"non-stop"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>      Total_Stops <span class="sc">==</span> <span class="st">"1 stop"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>      Total_Stops <span class="sc">==</span> <span class="st">"2 stops"</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>      Total_Stops <span class="sc">==</span> <span class="st">"3 stops"</span> <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>      Total_Stops <span class="sc">==</span> <span class="st">"4 stops"</span> <span class="sc">~</span> <span class="dv">4</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create weekend indicator feature</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">weekend =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>      departure_day_of_week <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Sunday"</span>, <span class="st">"Saturday"</span>) <span class="sc">~</span> <span class="st">"Weekend"</span>,</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Weekday"</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply same transformations to test data</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>flight_data_test_processed <span class="ot">&lt;-</span> flight_data_test <span class="sc">%&gt;%</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">number_of_stops =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>      Total_Stops <span class="sc">==</span> <span class="st">"non-stop"</span> <span class="sc">~</span> <span class="dv">0</span>,</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>      Total_Stops <span class="sc">==</span> <span class="st">"1 stop"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>      Total_Stops <span class="sc">==</span> <span class="st">"2 stops"</span> <span class="sc">~</span> <span class="dv">2</span>,</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>      Total_Stops <span class="sc">==</span> <span class="st">"3 stops"</span> <span class="sc">~</span> <span class="dv">3</span>,</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>      Total_Stops <span class="sc">==</span> <span class="st">"4 stops"</span> <span class="sc">~</span> <span class="dv">4</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">weekend =</span> <span class="fu">case_when</span>(</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a>      departure_day_of_week <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">"Sunday"</span>, <span class="st">"Saturday"</span>) <span class="sc">~</span> <span class="st">"Weekend"</span>,</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">"Weekday"</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Training samples: 8477 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Test samples: 1043 </code></pre>
</div>
</div>
</section>
</section>
<section id="model-development" class="level1">
<h1>Model Development</h1>
<section id="baseline-decision-tree-model" class="level2">
<h2 class="anchored" data-anchor-id="baseline-decision-tree-model">Baseline Decision Tree Model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Define core features for baseline model</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>baseline_features <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Departure_Day"</span>, <span class="st">"Departure_Month"</span>, <span class="st">"Departure_Hour"</span>, </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Duration_Hours"</span>, <span class="st">"number_of_stops"</span>, <span class="st">"weekend"</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"Airline"</span>, <span class="st">"airport_code_arrival"</span>, <span class="st">"airport_code_departure"</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"airport_code_first_stop"</span>, <span class="st">"airport_code_second_stop"</span>, </span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>                      <span class="st">"airport_code_third_stop"</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit baseline decision tree</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>model_baseline <span class="ot">&lt;-</span> <span class="fu">rpart</span>(</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  Price <span class="sc">~</span> Departure_Day <span class="sc">+</span> Departure_Month <span class="sc">+</span> Departure_Hour <span class="sc">+</span> Duration_Hours <span class="sc">+</span> </span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>         number_of_stops <span class="sc">+</span> weekend <span class="sc">+</span> Airline <span class="sc">+</span> airport_code_arrival <span class="sc">+</span> </span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>         airport_code_departure <span class="sc">+</span> airport_code_first_stop <span class="sc">+</span> </span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>         airport_code_second_stop <span class="sc">+</span> airport_code_third_stop,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> flight_data_train_processed, </span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"anova"</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== Baseline Model Summary ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression tree:
rpart(formula = Price ~ Departure_Day + Departure_Month + Departure_Hour + 
    Duration_Hours + number_of_stops + weekend + Airline + airport_code_arrival + 
    airport_code_departure + airport_code_first_stop + airport_code_second_stop + 
    airport_code_third_stop, data = flight_data_train_processed, 
    method = "anova")

Variables actually used in tree construction:
[1] Airline                 airport_code_arrival    airport_code_first_stop
[4] Departure_Day           Duration_Hours         

Root node error: 1.8328e+11/8477 = 21620496

n= 8477 

        CP nsplit rel error  xerror     xstd
1 0.423638      0   1.00000 1.00018 0.043194
2 0.047653      1   0.57636 0.57655 0.039455
3 0.042021      2   0.52871 0.52887 0.038683
4 0.033109      4   0.44467 0.44618 0.028517
5 0.016548      5   0.41156 0.41481 0.028607
6 0.014576      6   0.39501 0.41311 0.027326
7 0.010000      7   0.38043 0.40298 0.026754</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize decision tree with cleaner formatting</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(model_baseline, </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">main =</span> <span class="st">"Baseline Decision Tree for Flight Price Prediction"</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">cex =</span> <span class="fl">0.6</span>,           <span class="co"># Smaller text</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">tweak =</span> <span class="fl">1.2</span>,         <span class="co"># Adjust text size</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">box.palette =</span> <span class="st">"Blues"</span>,</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">shadow.col =</span> <span class="st">"gray"</span>,</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">split.cex =</span> <span class="fl">0.8</span>,     <span class="co"># Size of split labels</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">nn.cex =</span> <span class="fl">0.7</span>)        <span class="co"># Size of node labels</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Decision-Tree-Quarto_files/figure-html/baseline-visualization-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Baseline Decision Tree Structure</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Key Insights from Baseline Model:</strong> - The tree uses only 5 features: Airline, airport arrival code, first stop, departure day, and duration - Route structure (first stop) is the primary split, indicating it’s the most important pricing factor - The model achieves reasonable complexity with 7 splits, suggesting flight pricing follows interpretable business rules</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Complexity parameter analysis</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(model_baseline)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Decision-Tree-Quarto_files/figure-html/baseline-complexity-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Complexity Parameter Plot - Baseline Model</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="enhanced-decision-tree-model" class="level2">
<h2 class="anchored" data-anchor-id="enhanced-decision-tree-model">Enhanced Decision Tree Model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Enhanced model with additional temporal features</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>model_enhanced <span class="ot">&lt;-</span> <span class="fu">rpart</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  Price <span class="sc">~</span> Departure_Day <span class="sc">+</span> Departure_Month <span class="sc">+</span> Departure_Hour <span class="sc">+</span> Duration_Hours <span class="sc">+</span> </span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>         number_of_stops <span class="sc">+</span> weekend <span class="sc">+</span> Date_of_Journey <span class="sc">+</span> departure_date_time <span class="sc">+</span> </span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>         arrival_date_time <span class="sc">+</span> Airline <span class="sc">+</span> airport_code_arrival <span class="sc">+</span> </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>         airport_code_departure <span class="sc">+</span> airport_code_first_stop <span class="sc">+</span> </span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>         airport_code_second_stop <span class="sc">+</span> airport_code_third_stop,</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> flight_data_train_processed, </span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"anova"</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== Enhanced Model Summary ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression tree:
rpart(formula = Price ~ Departure_Day + Departure_Month + Departure_Hour + 
    Duration_Hours + number_of_stops + weekend + Date_of_Journey + 
    departure_date_time + arrival_date_time + Airline + airport_code_arrival + 
    airport_code_departure + airport_code_first_stop + airport_code_second_stop + 
    airport_code_third_stop, data = flight_data_train_processed, 
    method = "anova")

Variables actually used in tree construction:
[1] Airline                 airport_code_first_stop arrival_date_time      
[4] Date_of_Journey         Duration_Hours         

Root node error: 1.8328e+11/8477 = 21620496

n= 8477 

         CP nsplit rel error  xerror     xstd
1  0.423638      0   1.00000 1.00017 0.043164
2  0.112747      1   0.57636 0.57650 0.039452
3  0.039158      2   0.46362 0.46424 0.032283
4  0.034227      3   0.42446 0.42398 0.032337
5  0.033109      4   0.39023 0.41169 0.032288
6  0.018668      5   0.35712 0.36143 0.027220
7  0.013668      6   0.33845 0.34564 0.025477
8  0.012471      7   0.32478 0.33524 0.023979
9  0.010217      8   0.31231 0.31803 0.023812
10 0.010000      9   0.30210 0.31365 0.023915</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Enhanced visualization with better formatting</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(model_enhanced,</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>          <span class="at">main =</span> <span class="st">"Enhanced Decision Tree for Flight Price Prediction"</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">cex =</span> <span class="fl">0.5</span>,           <span class="co"># Even smaller text due to complexity</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">tweak =</span> <span class="fl">1.1</span>,         </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">box.palette =</span> <span class="st">"Greens"</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>          <span class="at">shadow.col =</span> <span class="st">"gray"</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>          <span class="at">split.cex =</span> <span class="fl">0.7</span>,     </span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>          <span class="at">nn.cex =</span> <span class="fl">0.6</span>,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>          <span class="at">fallen.leaves =</span> <span class="cn">TRUE</span>, <span class="co"># Better layout for complex trees</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>          <span class="at">extra =</span> <span class="dv">101</span>)         <span class="co"># Show node info more clearly</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Decision-Tree-Quarto_files/figure-html/enhanced-visualization-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Enhanced Decision Tree Structure</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Enhanced Model Analysis:</strong> - Adding temporal features (<code>Date_of_Journey</code>, <code>arrival_date_time</code>) improved the model complexity - The tree now incorporates specific dates, suggesting seasonal or time-based pricing patterns - Notice how the algorithm selected meaningful temporal splits, indicating airlines use dynamic pricing strategies</p>
</section>
<section id="deep-decision-tree-model" class="level2">
<h2 class="anchored" data-anchor-id="deep-decision-tree-model">Deep Decision Tree Model</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Deep tree with relaxed constraints</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>model_deep <span class="ot">&lt;-</span> <span class="fu">rpart</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  Price <span class="sc">~</span> Departure_Day <span class="sc">+</span> Departure_Month <span class="sc">+</span> Departure_Hour <span class="sc">+</span> Duration_Hours <span class="sc">+</span> </span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>         number_of_stops <span class="sc">+</span> weekend <span class="sc">+</span> Date_of_Journey <span class="sc">+</span> departure_date_time <span class="sc">+</span> </span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>         arrival_date_time <span class="sc">+</span> Airline <span class="sc">+</span> airport_code_arrival <span class="sc">+</span> </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>         airport_code_departure <span class="sc">+</span> airport_code_first_stop <span class="sc">+</span> </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>         airport_code_second_stop <span class="sc">+</span> airport_code_third_stop,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> flight_data_train_processed, </span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"anova"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">minsplit =</span> <span class="dv">8</span>,   <span class="co"># Minimum observations to attempt split</span></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">minbucket =</span> <span class="dv">2</span>,  <span class="co"># Minimum observations in terminal nodes  </span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">maxdepth =</span> <span class="dv">30</span>   <span class="co"># Maximum tree depth</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== Deep Model Summary ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression tree:
rpart(formula = Price ~ Departure_Day + Departure_Month + Departure_Hour + 
    Duration_Hours + number_of_stops + weekend + Date_of_Journey + 
    departure_date_time + arrival_date_time + Airline + airport_code_arrival + 
    airport_code_departure + airport_code_first_stop + airport_code_second_stop + 
    airport_code_third_stop, data = flight_data_train_processed, 
    method = "anova", minsplit = 8, minbucket = 2, maxdepth = 30)

Variables actually used in tree construction:
[1] Airline                 airport_code_first_stop arrival_date_time      
[4] Date_of_Journey         Duration_Hours         

Root node error: 1.8328e+11/8477 = 21620496

n= 8477 

         CP nsplit rel error  xerror     xstd
1  0.423638      0   1.00000 1.00028 0.043191
2  0.112747      1   0.57636 0.57682 0.039468
3  0.046227      2   0.46362 0.46435 0.032301
4  0.039158      3   0.41739 0.44788 0.030726
5  0.033109      4   0.37823 0.39790 0.028653
6  0.024940      5   0.34512 0.34924 0.020036
7  0.015863      6   0.32018 0.32584 0.018778
8  0.013668      7   0.30432 0.31387 0.016629
9  0.012471      8   0.29065 0.30341 0.016127
10 0.010217      9   0.27818 0.29001 0.015929
11 0.010000     10   0.26796 0.28146 0.015858</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(model_deep)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Decision-Tree-Quarto_files/figure-html/deep-visualization-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Deep Decision Tree Complexity Analysis</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Deep Model Insights:</strong> - Despite allowing much deeper trees (maxdepth = 30), the model only grew to 10 splits - showing natural complexity limits - <strong>Surprisingly, this model performed best</strong> on test data, suggesting the additional complexity captured meaningful pricing patterns - The complexity parameter plot shows the algorithm found optimal depth around 10-11 splits - <strong>Key finding</strong>: Airline pricing is more complex than initially assumed, but still follows interpretable rules</p>
</section>
</section>
<section id="model-comparison" class="level1">
<h1>Model Comparison</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Function to evaluate model performance</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>evaluate_model <span class="ot">&lt;-</span> <span class="cf">function</span>(model, test_data, model_name) {</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, test_data)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((test_data<span class="sc">$</span>Price <span class="sc">-</span> predictions)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  r_squared <span class="ot">&lt;-</span> (<span class="fu">cor</span>(test_data<span class="sc">$</span>Price, predictions))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(test_data<span class="sc">$</span>Price, predictions)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    <span class="at">Model =</span> model_name,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">RMSE =</span> <span class="fu">round</span>(rmse, <span class="dv">2</span>),</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">R_squared =</span> <span class="fu">round</span>(r_squared, <span class="dv">3</span>),</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">Correlation =</span> <span class="fu">round</span>(correlation, <span class="dv">3</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare all models</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>model_comparison <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">evaluate_model</span>(model_baseline, flight_data_test_processed, <span class="st">"Baseline"</span>),</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">evaluate_model</span>(model_enhanced, flight_data_test_processed, <span class="st">"Enhanced"</span>), </span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">evaluate_model</span>(model_deep, flight_data_test_processed, <span class="st">"Deep"</span>)</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== Model Performance Comparison ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     Model    RMSE R_squared Correlation
1 Baseline 2545.67     0.649       0.806
2 Enhanced 2350.81     0.698       0.836
3     Deep 2301.72     0.711       0.843</code></pre>
</div>
</div>
<p><strong>Model Comparison Insights:</strong> The results reveal an interesting progression:</p>
<ul>
<li><strong>Deep model wins</strong>: Despite allowing deeper complexity, the deep model achieved the best test performance (R² = 0.711) without overfitting</li>
<li><strong>Meaningful complexity</strong>: Each model improvement captured real pricing patterns:
<ul>
<li>Baseline (64.9% R²): Basic route and airline effects</li>
<li>Enhanced (69.8% R²): Temporal pricing patterns<br>
</li>
<li>Deep (71.1% R²): Complex route-time-airline interactions</li>
</ul></li>
<li><strong>Diminishing returns</strong>: The improvement rate decreased (4.9% → 1.3%), suggesting we’re approaching the natural limits of single tree models</li>
<li><strong>RMSE improvement</strong>: The deep model reduces prediction error by ~50 rupees compared to the enhanced model</li>
</ul>
<p>This suggests that airline pricing has more complexity than initially apparent, and the deeper tree successfully captures additional interactions.</p>
</section>
<section id="model-evaluation-using-best-model" class="level1">
<h1>Model Evaluation (Using Best Model)</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use the best performing model (Deep model performed best) for detailed evaluation</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>best_model <span class="ot">&lt;-</span> model_deep  </span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate predictions on test set</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(best_model, flight_data_test_processed)</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate evaluation metrics</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>rmse <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">mean</span>((flight_data_test_processed<span class="sc">$</span>Price <span class="sc">-</span> predictions)<span class="sc">^</span><span class="dv">2</span>))</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>r_squared <span class="ot">&lt;-</span> (<span class="fu">cor</span>(flight_data_test_processed<span class="sc">$</span>Price, predictions))<span class="sc">^</span><span class="dv">2</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>correlation <span class="ot">&lt;-</span> <span class="fu">cor</span>(flight_data_test_processed<span class="sc">$</span>Price, predictions)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>=== Best Model Performance Metrics ===</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>RMSE: 2301.72 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>R-squared: 0.711 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Correlation: 0.843 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add predictions to test data for visualization</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>flight_data_test_processed<span class="sc">$</span>predicted_price <span class="ot">&lt;-</span> predictions</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Create prediction scatter plot</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>flight_data_test_processed <span class="sc">%&gt;%</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Price, <span class="at">y =</span> predicted_price)) <span class="sc">+</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">size =</span> <span class="fl">1.5</span>, <span class="at">position =</span> <span class="fu">position_jitter</span>(<span class="at">width =</span> <span class="dv">50</span>)) <span class="sc">+</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">'lm'</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="dv">0</span>, <span class="at">slope =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Model Performance: Predicted vs Actual Flight Prices"</span>,</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="fu">paste</span>(<span class="st">"R² ="</span>, <span class="fu">round</span>(r_squared, <span class="dv">3</span>), <span class="st">"| RMSE ="</span>, <span class="fu">round</span>(rmse, <span class="dv">2</span>)),</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Actual Price (₹)"</span>,</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Predicted Price (₹)"</span></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Decision-Tree-Quarto_files/figure-html/prediction-analysis-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption>Predicted vs Actual Flight Prices</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Prediction Analysis Insights:</strong> The scatter plot reveals several important patterns:</p>
<ul>
<li><strong>Strong linear relationship</strong>: Points cluster around the diagonal line, indicating good predictive accuracy</li>
<li><strong>Discrete predictions</strong>: The vertical “bands” are characteristic of decision trees - each leaf node produces the same prediction for all samples that reach it</li>
<li><strong>Performance by price range</strong>: The model appears to perform well across different price ranges, though we see some scatter at higher price points</li>
<li><strong>Potential outliers</strong>: A few points far from the diagonal may represent special pricing scenarios (premium routes, last-minute bookings, etc.)</li>
</ul>
</section>
<section id="feature-importance-analysis" class="level1">
<h1>Feature Importance Analysis</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add feature importance analysis</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>feature_importance <span class="ot">&lt;-</span> best_model<span class="sc">$</span>variable.importance</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Feature importance plot</span></span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>feature_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Feature =</span> <span class="fu">names</span>(feature_importance),</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Importance =</span> feature_importance</span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>) <span class="sc">%&gt;%</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(Importance)) <span class="sc">%&gt;%</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>) <span class="sc">%&gt;%</span>  <span class="co"># Top 10 features</span></span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Feature =</span> <span class="fu">reorder</span>(Feature, Importance))</span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(feature_df, <span class="fu">aes</span>(<span class="at">x =</span> Feature, <span class="at">y =</span> Importance)) <span class="sc">+</span></span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Top 10 Feature Importance in Decision Tree"</span>,</span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Based on reduction in node impurity"</span>,</span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Features"</span>, </span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Importance Score"</span>) <span class="sc">+</span></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Decision-Tree-Quarto_files/figure-html/feature-importance-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Feature Importance Insights:</strong> The feature importance ranking reveals the hierarchy of pricing factors:</p>
<ol type="1">
<li><strong>Route structure dominates</strong>: <code>airport_code_first_stop</code> is by far the most important feature, indicating that connection patterns drive pricing more than individual airline policies</li>
<li><strong>Duration matters</strong>: Flight duration is the second most important factor, reflecting operational costs and passenger convenience pricing</li>
<li><strong>Engineered features work</strong>: Our <code>number_of_stops</code> feature ranks highly, validating the feature engineering approach</li>
<li><strong>Airline brand effects</strong>: Airline ranking suggests brand positioning impacts pricing, but less than route characteristics</li>
<li><strong>Temporal patterns</strong>: The presence of date/time features indicates dynamic pricing strategies</li>
</ol>
<p>This hierarchy makes business sense - route complexity and flight duration are fundamental cost drivers, while airline branding provides differentiation within those constraints.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Cross-validation for model selection</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>train_control <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>cv_model <span class="ot">&lt;-</span> <span class="fu">train</span>(Price <span class="sc">~</span> ., <span class="at">data =</span> flight_data_train_processed, </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">method =</span> <span class="st">"rpart"</span>, <span class="at">trControl =</span> train_control)</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>cv_model</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>CART 

8477 samples
  27 predictor

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 7630, 7628, 7630, 7629, 7629, 7629, ... 
Resampling results across tuning parameters:

  cp          RMSE      Rsquared   MAE     
  0.05049503  3228.953  0.5178657  2235.848
  0.10054449  3520.512  0.4263272  2421.670
  0.40049118  4244.984  0.3652703  3199.154

RMSE was used to select the optimal model using the smallest value.
The final value used for the model was cp = 0.05049503.</code></pre>
</div>
</div>
<p><strong>Cross-Validation Analysis:</strong> The cross-validation results provide crucial insights into model generalization:</p>
<ul>
<li><strong>Optimal complexity parameter</strong>: cp = 0.050 provides the best balance between bias and variance</li>
<li><strong>Expected performance</strong>: The CV R² of ~52% represents a more conservative (and realistic) estimate of model performance on new data</li>
<li><strong>Performance gap</strong>: The difference between CV performance (52%) and test set performance (71%) suggests either:
<ul>
<li>The test set has more predictable patterns than the training folds</li>
<li>Potential minor overfitting to test set characteristics</li>
<li>Natural variation in data splits</li>
</ul></li>
</ul>
<p>This gap is important for setting realistic expectations in production - we should expect closer to 52% R² on truly new, unseen data.</p>
</section>
<section id="residual-analysis" class="level1">
<h1>Residual Analysis</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Enhanced residual analysis</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>flight_data_test_processed <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">residuals =</span> Price <span class="sc">-</span> predicted_price) <span class="sc">%&gt;%</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> predicted_price, <span class="at">y =</span> residuals)) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.6</span>, <span class="at">color =</span> <span class="st">"darkblue"</span>) <span class="sc">+</span></span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"loess"</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">"orange"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Residual Analysis: Model Prediction Errors"</span>, </span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Points should be randomly scattered around zero line"</span>,</span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Predicted Price (₹)"</span>, </span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Residuals (Actual - Predicted)"</span>) <span class="sc">+</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Decision-Tree-Quarto_files/figure-html/residual-analysis-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<p><strong>Residual Analysis Insights:</strong> The residual plot reveals important model behavior patterns:</p>
<ul>
<li><strong>Centering</strong>: Residuals are well-centered around zero, indicating no systematic bias in predictions</li>
<li><strong>Homoscedasticity</strong>: The spread of residuals is relatively consistent across prediction ranges, suggesting stable model variance</li>
<li><strong>Decision tree artifacts</strong>: The vertical “bands” reflect the discrete nature of tree predictions - each leaf node gives the same prediction</li>
<li><strong>Outlier identification</strong>: Large positive residuals (&gt;5000) may indicate special pricing scenarios the model doesn’t capture well</li>
<li><strong>No major patterns</strong>: The absence of curved patterns suggests the linear relationships are appropriately captured</li>
</ul>
<p>The loess smoothing line helps identify any subtle non-linear patterns in the residuals that might suggest model improvements.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Analyze outliers for business insights</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>outliers <span class="ot">&lt;-</span> flight_data_test_processed <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">residuals =</span> Price <span class="sc">-</span> predicted_price) <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">abs</span>(residuals) <span class="sc">&gt;</span> <span class="dv">5000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Price, predicted_price, residuals, Airline, airport_code_arrival, </span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>         Duration_Hours, number_of_stops, weekend) <span class="sc">%&gt;%</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(<span class="fu">abs</span>(residuals)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Outlier Analysis Insights</strong></p>
<p>The 26 significant outliers reveal interesting patterns:</p>
<ul>
<li><strong>Premium airlines</strong> (Vistara, Jet Airways) dominate large prediction errors</li>
<li>DEL and COK routes appear frequently - suggesting <strong>complex pricing on these routes</strong></li>
<li><strong>Duration extremes</strong> (very short 2.7h and very long 25.9h flights) are harder to predict</li>
<li>This suggests airlines use <strong>special pricing rules</strong> for premium routes and unusual flight patterns</li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>=== Outlier Analysis ===</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of significant outliers (&gt;5000 rupees error): 26 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Price predicted_price residuals           Airline airport_code_arrival
1  21520        9067.781 12452.219           Vistara                  DEL
2  26890       15930.223 10959.777       Jet Airways                  DEL
3  23267       12871.041 10395.959          SpiceJet                  DEL
4  19644       11871.046  7772.954       Jet Airways                  COK
5  19360       11871.046  7488.954 Multiple carriers                  COK
6  11982        4817.204  7164.796           Vistara                  CCU
7  18804       11871.046  6932.954       Jet Airways                  COK
8  18804       11871.046  6932.954       Jet Airways                  COK
9   9678       15930.223 -6252.223         Air India                  HYD
10 13790        7584.443  6205.557            IndiGo                  COK
   Duration_Hours number_of_stops weekend
1        2.666667               0 Weekday
2       25.916667               1 Weekday
3        7.916667               1 Weekday
4        7.333333               2 Weekday
5        7.666667               2 Weekend
6        2.333333               0 Weekday
7        7.333333               2 Weekend
8        7.333333               2 Weekday
9       16.500000               2 Weekday
10       5.916667               1 Weekday</code></pre>
</div>
</div>
</section>
<section id="route-airline-pricing-analysis" class="level1">
<h1>Route-Airline Pricing Analysis</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Enhanced airline-route pricing analysis</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>pricing_analysis <span class="ot">&lt;-</span> flight_data_train_processed <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Airline, airport_code_arrival) <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">avg_price =</span> <span class="fu">mean</span>(Price), </span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">price_sd =</span> <span class="fu">sd</span>(Price),</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">count =</span> <span class="fu">n</span>(),</span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">min_price =</span> <span class="fu">min</span>(Price),</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">max_price =</span> <span class="fu">max</span>(Price)) <span class="sc">%&gt;%</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(count <span class="sc">&gt;</span> <span class="dv">20</span>) <span class="sc">%&gt;%</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(avg_price)) <span class="sc">%&gt;%</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">price_range =</span> max_price <span class="sc">-</span> min_price,</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">cv_price =</span> price_sd <span class="sc">/</span> avg_price) <span class="co"># Coefficient of variation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "=== Airline-Route Pricing Strategy Analysis ==="</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 29 × 9
# Groups:   Airline [8]
   Airline     airport_code_arrival avg_price price_sd count min_price max_price
   &lt;chr&gt;       &lt;chr&gt;                    &lt;dbl&gt;    &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt;     &lt;dbl&gt;
 1 Jet Airways COK                     12674.    2894.  1243      4256     21954
 2 Jet Airways BLR                     11733.    2325.  1016      5608     15149
 3 Jet Airways DEL                     11046.    6845.   585      3359     54826
 4 Multiple c… COK                     10954.    3760.   966      5797     34608
 5 Air India   BLR                     10363.    3474.   393      4145     31945
 6 Air India   COK                     10002.    3248.   598      4487     28322
 7 Air India   DEL                      9271.    4658.   264      3758     31783
 8 Vistara     BLR                      9230.    1348.   147      7770     16932
 9 Air Asia    COK                      7812.    2109.    67      6151     13774
10 Vistara     CCU                      7579.    3982.    37      3687     11982
11 IndiGo      COK                      7282.    2301.   567      4729     16162
12 GoAir       COK                      6681.    3102.    64      3876     22794
13 Jet Airways HYD                      6581.    4637.   173      1840     24210
14 Vistara     COK                      6516.    1078.    35      5586     12411
15 Vistara     DEL                      6125.    2821.   145      4353     21730
# ℹ 14 more rows
# ℹ 2 more variables: price_range &lt;dbl&gt;, cv_price &lt;dbl&gt;</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize airline pricing strategies</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>pricing_analysis <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">15</span>) <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(<span class="fu">paste</span>(Airline, airport_code_arrival, <span class="at">sep =</span> <span class="st">"-"</span>), avg_price), </span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>             <span class="at">y =</span> avg_price)) <span class="sc">+</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">ymin =</span> avg_price <span class="sc">-</span> price_sd, <span class="at">ymax =</span> avg_price <span class="sc">+</span> price_sd), </span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a>                <span class="at">width =</span> <span class="fl">0.2</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Average Flight Prices by Airline-Route Combination"</span>,</span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Error bars show ±1 standard deviation"</span>,</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Airline-Destination"</span>, </span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Average Price (₹)"</span>) <span class="sc">+</span></span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Decision-Tree-Quarto_files/figure-html/pricing-visualization-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<p><strong>Airline-Route Pricing Insights:</strong> This analysis reveals distinct pricing strategies and market positioning:</p>
<p><strong>Premium Tier (&gt;₹10,000 avg):</strong> - Jet Airways dominates premium routes, especially to COK (Cochin) - Multiple carriers to COK suggests this is a high-value destination - Large price variations indicate dynamic pricing or service differentiation</p>
<p><strong>Mid-Market (₹6,000-10,000):</strong> - Air India and Vistara occupy the middle ground - More consistent pricing (lower standard deviations) suggests stable positioning</p>
<p><strong>Budget Segment (&lt;₹6,000):</strong> - SpiceJet and IndiGo consistently offer lower prices - Lower price variations suggest more standardized pricing models</p>
<p><strong>Route-Specific Patterns:</strong> - <strong>COK routes</strong> command premium across all airlines - possibly due to distance, demand, or airport costs - <strong>HYD routes</strong> tend to be more affordable - potentially indicating competitive market or lower demand - <strong>Price volatility</strong> varies significantly by airline-route, indicating different pricing strategies</p>
<p>This segmentation provides valuable insights for competitive positioning and market understanding.</p>
</section>
<section id="results-and-interpretation" class="level1">
<h1>Results and Interpretation</h1>
<section id="key-findings" class="level2">
<h2 class="anchored" data-anchor-id="key-findings">Key Findings</h2>
<ol type="1">
<li><p><strong>Model Performance</strong>: The deep decision tree achieves an R² of 0.711 on test data (best performance), though cross-validation suggests ~52% is more realistic for new data.</p></li>
<li><p><strong>Feature Hierarchy</strong>: Route structure (first stop) dominates pricing decisions, followed by flight duration and number of stops. This indicates operational factors outweigh brand positioning in pricing.</p></li>
<li><p><strong>Airline Segmentation</strong>: Clear pricing tiers exist with Jet Airways leading premium positioning, IndiGo/SpiceJet in budget segments, and others in between.</p></li>
<li><p><strong>Model Behavior</strong>: The decision tree provides interpretable rules but produces discrete predictions, leading to characteristic “banding” in prediction plots.</p></li>
</ol>
</section>
<section id="business-implications" class="level2">
<h2 class="anchored" data-anchor-id="business-implications">Business Implications</h2>
<ul>
<li><strong>Route Planning</strong>: Connection patterns and duration are primary cost drivers - direct flights to premium destinations command highest prices</li>
<li><strong>Competitive Strategy</strong>: Airline brand matters less than route characteristics, suggesting operational efficiency is key</li>
<li><strong>Dynamic Pricing</strong>: Temporal features influence pricing, indicating sophisticated revenue management systems</li>
<li><strong>Market Segmentation</strong>: Clear pricing tiers exist across airline-route combinations, enabling targeted strategies</li>
</ul>
</section>
</section>
<section id="limitations-and-future-work" class="level1">
<h1>Limitations and Future Work</h1>
<section id="current-limitations" class="level2">
<h2 class="anchored" data-anchor-id="current-limitations">Current Limitations</h2>
<ol type="1">
<li><strong>Discrete Predictions</strong>: Single trees produce limited prediction granularity</li>
<li><strong>Cross-Validation Gap</strong>: Performance difference between CV and test suggests generalization concerns<br>
</li>
<li><strong>Outlier Handling</strong>: Large prediction errors indicate some pricing scenarios aren’t well captured</li>
<li><strong>Feature Interactions</strong>: Simple trees may miss complex airline-route-timing interactions</li>
</ol>
</section>
<section id="recommendations-for-enhancement" class="level2">
<h2 class="anchored" data-anchor-id="recommendations-for-enhancement">Recommendations for Enhancement</h2>
<ol type="1">
<li><strong>Random Forest</strong>: Address discrete predictions and improve generalization</li>
<li><strong>Feature Engineering</strong>: Explore route complexity metrics, seasonal indicators, demand proxies</li>
<li><strong>Ensemble Methods</strong>: Combine multiple approaches for robust predictions</li>
<li><strong>Validation Strategy</strong>: Implement time-based splits to better reflect real-world deployment</li>
</ol>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This analysis demonstrates that decision trees effectively model flight pricing with meaningful business insights. The deep model achieved the strongest test performance (R² = 0.711), indicating that airline pricing has more complexity than initially apparent, yet still follows interpretable decision rules.</p>
<p>The model reveals that operational factors (route structure, duration) dominate pricing decisions over brand effects, and clear market segmentation exists across airline-route combinations. The interpretable nature of decision trees makes them valuable for stakeholder communication and business strategy development.</p>
<p>Future work should focus on ensemble methods to improve prediction granularity while maintaining interpretability, and more sophisticated feature engineering to capture complex pricing interactions.</p>
<hr>
<p><em>Analysis completed using R R version 4.5.1 (2025-06-13) with rpart package for decision tree modeling.</em></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>